#!/usr/bin/env bash
# =============================================================================
# setup-self-improvement.sh — Install Jake's self-improvement systemd timer
#
# Installs:
#   /usr/local/bin/jake-self-improve.sh    — the worker script
#   /etc/systemd/system/jake-self-improve.service
#   /etc/systemd/system/jake-self-improve.timer
#
# The timer fires every 6 hours by default.
# Jake can also trigger it manually via the self_improvement skill or:
#   sudo systemctl start jake-self-improve.service
#
# Idempotent: overwrites service/timer files; re-enables on re-run.
# Must run as root.
# =============================================================================
set -euo pipefail
[[ "${EUID}" -ne 0 ]] && { echo "Must run as root" >&2; exit 1; }

JAKE_USER="${JAKE_USER:-jake}"
JAKE_HOME="${JAKE_HOME:-/home/${JAKE_USER}}"
JAKE_DATA="${JAKE_DATA:-/Jake-data}"
JAKECLAW_DIR="${JAKECLAW_DIR:-/JakeClaw}"

# How often the timer fires (OnCalendar format)
# USER INPUT OPTIONAL: change to suit your preference
TIMER_SCHEDULE="${JAKE_IMPROVE_SCHEDULE:-*-*-* 02,08,14,20:00:00}"

log() { echo "[$(date '+%Y-%m-%dT%H:%M:%S')] [setup-self-improvement] $*"; }
log "Installing self-improvement systemd timer..."

# ─── Write the worker script ──────────────────────────────────────────────
cat > /usr/local/bin/jake-self-improve.sh << 'WORKER_EOF'
#!/usr/bin/env bash
# =============================================================================
# jake-self-improve.sh — Self-improvement worker (called by systemd)
# DO NOT edit this file directly; it is managed by setup-self-improvement.sh
# =============================================================================
set -euo pipefail

JAKE_USER="${JAKE_USER:-jake}"
JAKE_HOME="${JAKE_HOME:-/home/${JAKE_USER}}"
JAKE_DATA="${JAKE_DATA:-/Jake-data}"
JAKECLAW_DIR="${JAKECLAW_DIR:-/JakeClaw}"
LOCK_FILE="/var/lock/jake-self-improve.lock"
LOG_DIR="${JAKE_DATA}/logs"
LOG_FILE="${LOG_DIR}/self-improvement.log"

mkdir -p "${LOG_DIR}"

log() { echo "[$(date '+%Y-%m-%dT%H:%M:%S')] [self-improve] $*" | tee -a "${LOG_FILE}"; }
err() { echo "[$(date '+%Y-%m-%dT%H:%M:%S')] [self-improve] ERROR: $*" | tee -a "${LOG_FILE}" >&2; }

# ── Prevent concurrent runs ───────────────────────────────────────────────
exec 200>"${LOCK_FILE}"
flock -n 200 || {
  log "Another self-improvement run is in progress — skipping."
  exit 0
}

log "====== Self-improvement cycle START ======"

# ── 1. Git pull JakeClaw repo ─────────────────────────────────────────────
log "Pulling latest JakeClaw..."
if [[ -d "${JAKECLAW_DIR}/.git" ]]; then
  # Check for local modifications — never force-reset
  if su - "${JAKE_USER}" -c "git -C ${JAKECLAW_DIR} status --porcelain" | grep -q .; then
    log "WARNING: Local uncommitted changes in ${JAKECLAW_DIR} — skipping pull to preserve work."
    log "         Commit or stash changes for auto-pull to work."
  else
    su - "${JAKE_USER}" -c "git -C ${JAKECLAW_DIR} pull --ff-only 2>&1" || {
      err "git pull failed — skipping rebuild (repo state unchanged)"
      log "====== Self-improvement cycle END (pull failed) ======"
      exit 1
    }
    log "git pull OK"
  fi
else
  err "${JAKECLAW_DIR} is not a git repo — cannot pull"
fi

# ── 2. Rebuild claw-code if source changed ────────────────────────────────
HASH_FILE="/var/lib/jake/claw-installed-hash"
SRC_HASH=$(git -C "${JAKECLAW_DIR}/claw-code" rev-parse HEAD 2>/dev/null || echo "none")

if [[ -f "${HASH_FILE}" ]] && [[ "$(cat "${HASH_FILE}")" == "${SRC_HASH}" ]]; then
  log "Claw-code source unchanged (${SRC_HASH:0:8}) — skipping rebuild"
else
  log "Claw-code source changed — rebuilding..."

  # Backup current binary before rebuild
  if [[ -f /usr/local/bin/claw ]]; then
    cp /usr/local/bin/claw /usr/local/bin/claw.bak
    log "Backed up current claw binary to claw.bak"
  fi

  # Rebuild
  if bash "${JAKECLAW_DIR}/scripts/install-claw-code.sh" >> "${LOG_FILE}" 2>&1; then
    log "Claw-code rebuild SUCCESS"
    echo "${SRC_HASH}" > "${HASH_FILE}"
  else
    err "Claw-code rebuild FAILED"
    # Rollback to backup
    if [[ -f /usr/local/bin/claw.bak ]]; then
      cp /usr/local/bin/claw.bak /usr/local/bin/claw
      log "ROLLED BACK to claw.bak"
    fi
    log "====== Self-improvement cycle END (rebuild failed, rolled back) ======"
    exit 1
  fi
fi

# ── 3. Reload / regenerate dynamic skills ────────────────────────────────
log "Regenerating dynamic claw skills..."
if bash "${JAKECLAW_DIR}/scripts/expose-claw-tools.sh" >> "${LOG_FILE}" 2>&1; then
  log "Dynamic skills regenerated OK"
else
  log "WARNING: expose-claw-tools.sh returned non-zero — skills may be stale"
fi

# ── 4. Restart affected services ──────────────────────────────────────────
log "Restarting claw-code.service and jake-api.service..."
systemctl restart claw-code.service 2>/dev/null || log "Note: claw-code.service restart skipped"
systemctl restart jake-api.service  2>/dev/null || log "Note: jake-api.service restart skipped"

log "====== Self-improvement cycle END (SUCCESS) ======"
WORKER_EOF

chmod +x /usr/local/bin/jake-self-improve.sh

# ─── Systemd service ──────────────────────────────────────────────────────
cat > /etc/systemd/system/jake-self-improve.service << EOF
[Unit]
Description=Jake Self-Improvement Cycle
After=network.target claw-code.service

[Service]
Type=oneshot
User=root
ExecStart=/usr/local/bin/jake-self-improve.sh
Environment="JAKE_USER=${JAKE_USER}"
Environment="JAKE_HOME=${JAKE_HOME}"
Environment="JAKE_DATA=${JAKE_DATA}"
Environment="JAKECLAW_DIR=${JAKECLAW_DIR}"
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

# ─── Systemd timer ────────────────────────────────────────────────────────
cat > /etc/systemd/system/jake-self-improve.timer << EOF
[Unit]
Description=Jake Self-Improvement Timer
After=network.target

[Timer]
# USER INPUT OPTIONAL: change schedule here or in JAKE_IMPROVE_SCHEDULE env var
OnCalendar=${TIMER_SCHEDULE}
RandomizedDelaySec=300
Persistent=true
Unit=jake-self-improve.service

[Install]
WantedBy=timers.target
EOF

# ─── Enable and start ─────────────────────────────────────────────────────
mkdir -p /var/lib/jake
systemctl daemon-reload
systemctl enable jake-self-improve.timer
systemctl start  jake-self-improve.timer

log "Self-improvement timer installed and active"
log "Schedule: ${TIMER_SCHEDULE}"
log "Status: $(systemctl is-active jake-self-improve.timer)"
log "Manual run: sudo systemctl start jake-self-improve.service"
log "Logs: ${JAKE_DATA}/logs/self-improvement.log"
